
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.synced_folder ".", "/shared"
  
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  
  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--memory", 2048]
  end

  config.vm.provision "shell", inline: <<-SHELL
	  sudo apt-get update
	  sudo apt-get upgrade -y
	  sudo curl -fsSL get.docker.com -o get-docker.sh
      sudo sh get-docker.sh
	  sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
	  sudo chmod +x /usr/local/bin/docker-compose
	  sudo mkdir /docker
	  sudo cp /shared/docker-compose.yml /docker/docker-compose.yml
	  cd /docker
	  sudo docker-compose up --scale mariadb-master=1 --scale mariadb-slave=3 -d
  SHELL
end
