
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.synced_folder ".", "/shared"
  
  config.vm.network "forwarded_port", guest: 4800, host: 4800

  config.vm.provision "shell", inline: <<-SHELL
	  sudo apt-get update
	  sudo apt-get install docker-ce -y
	  sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
	  sudo chmod +x /usr/local/bin/docker-compose
	  sudo mkdir /docker
	  sudo cp /shared/docker-compose.yml /docker/docker-compose.yml
	  sudo docker-compose up -d
  SHELL
end
